config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get "/about" => "home#about"

  get '/contact' => "contacts#new"
  get '/confirm' => "contacts#confirm"
  get '/edit' => "contacts#edit"
  get '/thanks!' => "contacts#thanks"

  resources :contacts,only: [:new,:create,:edit,:update] do
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name,              presence: true
  validates :ruby,              presence: true
  validates :email,             presence: true
  validates :item,              presence: true
  validates :content,           presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    session[:name] = contact_params[:name]
    session[:ruby] = contact_params[:ruby]
    session[:email] = contact_params[:email]
    session[:item] = contact_params[:item]
    session[:content] = contact_params[:content]

    @contact = Contact.new(contact_params) 

    @item = contact_params[:item]

    if @contact.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :new
    end
  end

  def create
    @contact = Contact.new(
      name: session[:name], 
      ruby: session[:ruby], 
      email: session[:email],
      item: session[:item], 
      content: session[:content]
    )
    if @contact.save
      redirect_to "/thanks!"
    else
      render :new
    end
  end

  def edit
    @contact = Contact.new(
      name: session[:name], 
      ruby: session[:ruby], 
      email: session[:email],
      item: session[:item], 
      content: session[:content]
    )

    @item = @contact.item
    render :new
  end  

  def thanks

  end

  private

  def contact_params
    params.permit(:name, :ruby, :email, :item, :content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/confirm.html.erb
<body>
  <div class="contact-inner">
    <%= form_tag("submit_path") do |f| %>
        <h1 class="contact-title">お問い合わせ 内容確認</h1>
        <p class="contact-discription-confirm">お問い合わせ内容をご確認の上、よろしければ「送信する」ボタンをクリックしてください。</p>
        <div class="form-container form-container-confirm">
            <div class="form">
              <div class="form-left" style="width: 50%;">
                <label class="label">お名前</label>
              </div>  
              <div class="form-left" style="width: 50%;">
                <h3><%=@contact.name%></h3>
              </div>  
            </div>
            <div class="form">
              <div class="form-left" style="width: 50%;">
                <label>ふりがな</label>
              </div>  
              <div class="form-left" style="width: 50%;">
                <h3><%=@contact.ruby%></h3>
              </div>  
                
            </div>
            <div class="form">
              <div class="form-left" style="width: 50%;">
                <label>メールアドレス</label>
               </div>
               <div class="form-left" style="width: 50%;">
                <h3><%=@contact.email%></h3>
              </div>  
                
            </div>
            <div class="form">
              <div class="form-left" style="width: 50%;">
                <label>お問い合わせ項目</label>
              </div>  
              <div class="form-left" style="width: 50%;">
                <h3><%=@contact.item%></h3>
              </div>  
                
                
            </div>
            <div class="form">
              <div class="form-left" style="width: 50%;">
                <label>お問い合わせ内容</label>
              </div>  
              <div class="content-box">
                <h3 class="content-confim"><%=@contact.content %></h3>
              </div>  
            </div>
        </div>
        <div class="button-clearfix" style="padding-top: 30px;">
          <%= link_to "内容を修正する", "/edit", class:"edit-btn" %>
          <%= link_to "送信する", contacts_path, method: :post, class:"submit-btn" %>
        </div>  
    <% end %>
  </div>
</body>

app/views/contacts/new.html.erb
<body>
  <div class="contact-inner">
    <%= form_tag(confirm_path, method: :get) do |f| %>
        <h1 class="contact-title">お問い合わせ 内容入力</h1>
        <p class="contact-discription">お問い合わせ内容をご入力の上、「確認画面へ」ボタンをクリックしてください。</p>
        <div class="form-container">
            <div class="form">
              <div class="form-left">
                <label class="label">お名前<span class="require">必須</span></label>
              </div>  
                <input name="name" id="name" placeholder="例）山田太郎" value="<%= @contact.name %>">
            </div>
            <div class="form">
              <div class="form-left">
                <label>ふりがな<span class="require">必須</span></label>
              </div>  
                <input name="ruby" id="ruby" placeholder="例）やまだたろう" value="<%= @contact.ruby %>">
            </div>
            <div class="form">
              <div class="form-left">
                <label>メールアドレス<span class="require">必須</span></label>
               </div>
                <input name="email" id="email" placeholder="例）guest@example.com" value="<%= @contact.email %>">
            </div>
            <div class="form">
              <div class="form-left">
                <label>お問い合わせ項目<span class="require">必須</span></label>
              </div>  
              <% if current_page?(edit_path) %>
                <select name="item" id="item" >
                    <option value="#{@item}" class="defo"><%= @item %></option>
                    <option value="ご質問・お問い合わせ">ご質問・お問い合わせ</option>
                    <option value="ご意見・ご感想">ご意見・ご感想</option>
                </select>
              <% else%>
                <select name="item" id="item">
                    <option value="" class="defo">お問い合わせ項目を選択してください</option>
                    <option value="ご質問・お問い合わせ">ご質問・お問い合わせ</option>
                    <option value="ご意見・ご感想">ご意見・ご感想</option>
                </select>
              <% end %>  
            </div>
            <div class="form">
              <div class="form-left">
                <label>お問い合わせ内容<span class="require">必須</span></label>
              </div>  
                <textarea placeholder="お問合せ内容を入力" rows="5" name="content" id="content"><%= @contact.content %></textarea>
            </div>
        </div>
        <div class="button-clearfix">
            <button type="submit" id="contact_send">確認画面へ</button>
        </div>  
    <% end %>
  </div>
</body>

app/views/contacts/thanks.html.erb
<body>
  <div class="contact-inner">
    <div class="thanks-wrapper">
        <h1 class="contact-title ">お問い合わせ 送信完了</h1>
        <p class="contact-discription-thanks">
        お問い合わせありがとうございました。<br>
        内容を確認のうえ、回答させて頂きます。<br>
        しばらくお待ちください。
        </p>
        <div  class="button-thanks-clearfix">
          <a href="/">
              <button class="button-thanks">トップに戻る</button>
          </a>
          <a href="/contact">
              <button class="button-thanks">お問い合わせに戻る</button>
          </a>
        </div>  
    </div>
  </div>
</body>

app/views/home/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  
  
  <%# <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> %>
  
  <%# <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/> %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <title>会社概要</title>
  <%# <%= csrf_meta_tags %> %>
  <%# <%= csp_meta_tag %> %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%# <%= javascript_include_tag 'application' %> %>
</head>
<body>
  
  <div class=body-inner>
    <div class=title>
      <a><h1 class="company-name-about"><i class="far fa-building"></i>　会社概要　<i class="far fa-building"></i></h1></a>
    </div>
    <div class=key>
      <h1>代表者名</h1> 
    </div>
    <div class=value>
      <h2>久野 真也</h2>
    </div>
    <div class=key>
      <h1>住所</h1>
    </div>
    <div class=value-map>
      <h2>〒840-0815佐賀県佐賀市天神１丁目２番５５号 益本天神ビル５Ｆ</h2>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3336.262248494102!2d130.29442831519438!3d33.25962608082904!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3541ca6da81c02bf%3A0x4bbc1c47129449ac!2z44CSODQwLTA4MTUg5L2Q6LOA55yM5L2Q6LOA5biC5aSp56We77yR5LiB55uu77yS4oiS77yV77yVIOebiuacrOWkqeelnuODk-ODqyDvvJXvvKY!5e0!3m2!1sja!2sjp!4v1578638687621!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
    <div class=key>
      <h1>事業内容</h1>
    </div>
    <div class=value>
      <h2>飲食店経営（佐賀市内に７店舗、長崎市内に１店舗、大分市内に１店舗）</h2>
    </div>
    <div class=key>
      <h1>従業員数</h1>
    </div>
    <div class=value>
      <h2>企業全体:120人</h2>
    </div>
    <div class=key>
      <h1>法人番号</h1>
    </div>
    <div class=value>
      <h2>4300001008058</h2>
    </div>
    <div class=key>
      <h1>関連会社</h1>
    </div>
    <div class=value>
      <h2>U.アソシエート株式会社　　一般社団法人あすなろサポート</h2>
    </div>
  </div>  
</body>  

app/views/home/top.html.erb
<!DOCTYPE html>

<body>
  
  <section class=concept>
    <div class=concept-innner>
      <h3 class=concept-title>地元の方においしさを届ける</h3>
      <p class=concept-text>当社は、飲食事業を通じて、<br>地元の方々に愛される会社を目指します。</p>
    </div>
  </section>
  <%# <section class=servise-contents> %>
    <%# <h1 class=service-list-font>Servicce list</h1> %>
  <%# </section> %>
  <section class=servise id="servise">
    <div class=service-inner>
      <ul class=contents-row-one>
        <li class=content>
          <a href="http://tomoru.area9.jp/" target="_blank"><img src="https://uds.gnst.jp/rest/img/r77wg72e0000/s_0na2.jpg"></a>
          <p><b class="store-name">Tomoru</b><br><br>☎︎(0952)33-5133<br>〒849-0937<br>佐賀市鍋島2-5-27</p>
        </li>
        <li class=content>
          <a href="http://roku.area9.jp/" target="_blank"><img src="https://uds.gnst.jp/rest/img/eau75p8y0000/s_0n7e.jpg"></a>
          <p><b class="store-name">禄</b><br><br>☎︎(0952)27-6266<br>〒840-0812<br>佐賀市愛敬町13-13</p>
        </li>
        <li class=content>
          <a href="https://www.anbata-enbata.com/" target="_blank"><img src="https://www.anbata-enbata.com/assets/images/page/topHeader02.jpg"></a>
          <p><b class="store-name">あんバター∞えんバター</b><br><br>☎︎(0952)37-1025<br>〒840-0801<br>佐賀市駅前中央1丁目13-8</p>
        </li>
      </ul>
      <ul class=contents-row-two>
        <li class=content>
          <a href="http://tomoruya.area9.jp/" target="_blank"><img src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/11002619_639706062842469_1185099978879054427_n.jpg?_nc_cat=102&_nc_ohc=SyoNu8K_KCgAQls2dXBB7LDLdUzbqTjBKibX7qeNHh5OQRA7xFTkQG7XA&_nc_ht=scontent-nrt1-1.xx&oh=fb1691e854a636b8f2588d8c8233d67f&oe=5E9F5339"></a>
          <p><b class="store-name">Tomoru屋</b><br><br>☎︎(0952)26-6001<br>〒840-0824<br>佐賀市呉服元町6-8</p>
        </li>
        <li class=content>
          <a href="https://r.gnavi.co.jp/djbm5g290000/" target="_blank"><img src="http://tomoru.area9.jp/image/banner_ultra.jpg"></a>
          <p><b class="store-name">うる寅</b><br><br>☎︎(0952)97-6650<br>〒840-0831<br>佐賀市松原町2丁目1-15</p>
        </li>
        <li class=content>
          <a href="https://www.celeb-kojo.com/" target="_blank"><img src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/56472462_575412369624336_3467451514673430528_o.png?_nc_cat=109&_nc_ohc=UV1ySqfK_7sAQmbBF1QYFQpTtxOCjxc_4AzPefBPDI7p8M38u-aKCYTkg&_nc_ht=scontent-nrt1-1.xx&oh=1835e66ca54e9cf0ef429a3404216354&oe=5EA07BF2"></a>
          <%# <p class=store-address>浜町店</p> %>
          <p><b class="store-name">セレブ工場（浜町店）</b><br><br>☎︎(095)801-0411<br>〒801-0411<br>長崎県長崎市浜町6-22</p>
        </li>
      </ul>
      <ul class=contents-row-three>
        <li class=content>
          <a href="http://tomozo.area9.jp/" target="_blank"><img src="https://www.suntory.co.jp/shop_img/l/0X00296033_l1.jpg"></a>
          <p><b class="store-name">とも蔵</b><br><br>☎︎(0952)29-1955<br>〒840-0801<br>佐賀市駅前中央1-4-6<br>モードビル5　3F</p>
        </li>
        <li class=content>
          <a href="https://sagagourmet.sagafan.jp/e910463.html" target="_blank"><img src="https://media-cdn.tripadvisor.com/media/photo-s/15/00/e2/d3/2.jpg"></a>
          <p><b class="store-name">HARU cafe</b><br><br>☎︎(0952)37-3366<br>〒840-0831<br>佐賀市松原2丁目2-27<br>バルーンミュージアム2F</p>
        </li>
        <li class=content>
          <a href="https://www.celeb-kojo.com/" target="_blank"><img src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/56472462_575412369624336_3467451514673430528_o.png?_nc_cat=109&_nc_ohc=UV1ySqfK_7sAQmbBF1QYFQpTtxOCjxc_4AzPefBPDI7p8M38u-aKCYTkg&_nc_ht=scontent-nrt1-1.xx&oh=1835e66ca54e9cf0ef429a3404216354&oe=5EA07BF2"></a>
          <%# <p class=store-address>府内町店</p> %>
          <p><b class="store-name">セレブ工場（府内町店）</b><br><br>☎︎(097)574-7451<br>〒870-0021<br>大分県大分市府内町3丁目2-21</p>
        </li>
      </ul>
      </ul>  
    </div>
  </section>
  <section class=initiatives>
    <a href="https://ballooners.jp/" target="_blank" class="ballooners"><img src="https://www.bleague.jp/files/user/common/img/logo/m/sg.png" style="padding-top: 50px; alt="佐賀バルーナーズ"></a>
    <div class=initiatives-text-box>
      <p class=initiatives-text>
        私たちは佐賀バルーナーズを応援しています。
      </p>
    </div>
  </section>
  <footer>
    <div class=footer-menu-innner>
      <ul class=footer-menu-clearfix>
        <li class=home>
          <a href="">株式会社クーイング</a>
        </li>
        <li class=overview>
          <a href="/about">会社概要</a>
        </li>
        <li class=privacy-policy>
          <a>プライバシーポリシー</a>
        </li>
      </ul>
    </div class=footer-menu-innner>
    <div class=copy>
      <p class=copy-text>
        Copyright COOING Co.,Ltd. All Rights Reserved.
      </p>
    </div>
  </footer>
<script src="script.js"></script>  
</body>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
  <title>cooing</title>
  <script src="https://js.pay.jp/" type="text/javascript"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://js.pay.jp/" type="text/javascript"></script>
  <script src="https://www.google.com/recaptcha/api.js?hl=ja"></script>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
  <title>FreemarketSample67d</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
  <body>
    <header>
      <div class="header-logo">
        <h1 class=campany-name><a href="/">COOING Co.,Ltd</a></h1>
      </div>
      <div class=nav>
        <div class=nav-menu>
          <ul class=nav-menu-clearfix>
            <% if current_page?(about_path) %>
              <div class=menu-now>
                <%= link_to 'ABOUT', "/about" %>
              </div>
            <% else %>  
              <div class=menu>
                <%= link_to 'ABOUT', "/about", class:"about"%>
              </div>
            <% end %>  
            <div class=menu>
              <a href="/#servise" class="service">SERVISE</a>
              <div class=service-lists-js>
                <div class="service-list-js">
                  <a href="http://tomoru.area9.jp/">Tomoru</a><br><a href="http://tomoruya.area9.jp/">Tomoru屋</a><br><a href="http://tomozo.area9.jp/">とも蔵</a><br><a href="http://roku.area9.jp/">禄</a><br><a href="https://r.gnavi.co.jp/djbm5g290000/">うる寅</a><br><a href="https://sagagourmet.sagafan.jp/e910463.html">HARUcafe</a><br><a href="https://www.anbata-enbata.com/">あんバター∞えんバター</a><br><a href="https://www.celeb-kojo.com/">セレブ工場(浜町店)</a><br><a href="https://www.celeb-kojo.com/">セレブ工場(府内町店)</a>
                </div>
              </div>
            </div>
            <div class=menu>
              <a>RECRUIT</a>
              <p></p>
            </div >
            <% if current_page?(contact_path) %>
              <div class=menu-now>
                <%= link_to 'CONTACT', "/contact", class:"contact"%>
              </div>
            <% else %>  
              <div class=menu>
              <a href="/contact">CONTACT</a>
            </div>
            <% end %>  
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>